[package]
name = "ev3robot"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["macros"]

[dependencies]
anyhow = "1"
bitflags = "1"
derive_more = "0.99"
ev3robot_macros = { path = "macros" }
tap = "1"
thiserror = "1"
